config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'sessions/new'

  resources :users do
    get :change_permission, on: :member
  end

  resources :categories do
    resources :posts
  end

  resources :sessions

  resources :posts do
    get :favourite, on: :member
    resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'
  get 'auth/:provider/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/favourite_post.rb
class FavouritePost < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def self.manage(post)
    object = find_by(post: post)
    object ? object.destroy : create(post: post)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
  validates :body,  presence: true

  has_many :comments, dependent: :destroy
  has_many :favourite_posts
  belongs_to :user
  has_and_belongs_to_many :categories

  mount_uploader :image, ImageUploader

  self.per_page = 6
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email
  validates_presence_of :email
  validates_presence_of :password, on: :create

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  has_many :accounts, dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  self.per_page = 10

  def full_name
    "#{name} aka #{lastname}"
  end
end

app/controllers/admin/application_controller.rb
#
class Admin::ApplicationController < ActionController::Base
end

app/controllers/admin/posts_controller.rb
#
class Admin::PostsController < AdminsController
  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end
end

app/controllers/admin/users_controller.rb
#
class Admin::UsersController < AdminsController
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
    @current_user.try(:admin)
  end

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize, only: [:create, :destroy]
  before_action :current_comment

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def current_comment
    @post = Post.find(params[:post_id])
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  before_action :current_resources

  def create
    if @user
      @account[user: @user]
    else
      @user = @account.create_user(vk_params)
    end
    @account.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private

  def current_resources
    @account = Account.find_or_create_by(uid: auth_hash[:uid],
                                         provider: auth_hash[:provider],
                                         email: auth_hash[:info][:email])
    @user = User.find_by(email: auth_hash[:info][:email])
  end

  def vk_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
    {
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:extra][:raw_info][:photo_400],
      password: password,
      password_confirmation: password
    }
  end

  def fb_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
    {
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:extra][:raw_info][:photo_400],
      password: password,
      password_confirmation: password
    }
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_post,
                only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories)
                 .order(created_at: :desc)
                 .page(params[:page])
  end

  def new
    redirect_to root_path unless current_user
    @post = Post.new
    @category = Category.all
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post.increment!(:page_views)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def favourite
    current_user.favourite_posts.manage(@post)
  end

  private

  def current_post
    @post = Post.find(params[:id])
    if params[:category_id]
      @category = Category.find params[:category_id]
      @posts = @category.posts
    else
      @posts = Post.all
    end
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, category_ids: [])
  end

  def require_user
    redirect_to root_path unless current_user == @post.user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_resourse,
                only: [:show, :edit, :update, :change_permission, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to :back
  end

  def edit
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end

  private

  def current_resourse
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :lastname, :email,
                                 :password, :password_confirmation,
                                 :avatar, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def require_user
    current_user == @post.user
  end

  def favourite_post(post)
    if current_user && current_user.favourite_posts.map(&:post).include?(post)
      'text-info'
    else
      'text-muted'
    end
  end
end

app/views/admin/posts/destroy.js.erb
$('#post_<%= @post.id %>').remove();

app/views/admin/posts/index.html.erb
<table class='table table-hover'>
  <thead>
  	<tr>
  	  <th>Post</th>
  	  <th></th>
  	</tr>
  </thead>
  <tbody>
  	<% @posts.each do |post| %>
      <tr id = <%= "post_#{post.id}" %>>
        <td><%= link_to post.title, post %></td>
        <td>
          <h4>
          	<%= link_to 'Delete', admin_post_path(post), class: 'label label-danger', method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
          </h4>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/destroy.js.erb
$('#user_<%= @user.id %>').remove();

app/views/admin/users/index.html.erb
<table class='table table-hover'>
  <thead>
  	<tr>
  	  <th>Email</th>
  	  <th>Avatar</th>
  	  <th></th>
  	</tr>
  </thead>
  <tbody>
  	<% @users.each do |user| %>
      <tr id = <%= "user_#{user.id}" %>>
        <td><%= link_to user.email, user %></td>
        <td><%= image_tag user.avatar.url(:small), class: 'img-circle' %></td>
        <td>
          <h4>
          <% if user.admin %>
            <%= link_to 'make user', change_permission_user_path(user), class: 'label label-primary'%>
          <% else %>
            <%= link_to 'make admin', change_permission_user_path(user), class: 'label label-warning' %>
          <% end %>
            <%= link_to 'Delete', admin_user_path(user), class: 'label label-danger', method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></h4>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/_comment.html.erb
<div class='row margin-comment'>
  <% if comment.body %>
    <div class='col-xs-1'>
      <%= image_tag comment.user.avatar.url(:small), class: 'img-circle user_image_small' unless comment.user.blank? %> 
    </div>
    <div class='col-xs-8'>
      <strong> <%= comment.user.email %></strong>
      <p><text><%= comment.body %></text></p>
      <p class='comment_time'><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>
    <div class='col-xs-3'>
      <% if current_user %>
        <% if current_user.id == comment.user_id %>
          <%= link_to 'Destroy', [comment.post, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% else %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, class: 'form-control article-textarea' %>
  </p>
  <br>
  <p>
    <button class='button'>
      <%= f.submit class: 'btn btn-success'%>
    </button>
  </p>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/admin/header' %>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: 'alert') %>
  <% end %>
  <div class = "container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/sidebar' %>
  <div id="main_content">
    <%= render 'shared/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: 'alert') %>
    <% end %>
      <%= yield %>
      <%= render 'shared/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id = 'page_wrapper'>
  <div class = 'row'>
    <div id = 'content'>
      <div class = 'media'>
        <div class = 'col-md-6 col-xs-12'>
          <div class = 'media-left media-middle'>
            <div id = 'profile_image'>
              <%= image_tag '/assets/profile.jpg' %>
            </div>
          </div>
        </div>
        <div class = 'col-md-6 col-xs-12'>
          <div class='media-body'>
            <h2>Hello</h2>
            <p>My name is Danil. This is a my blog</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <div class="alert alert-dismissible alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h1>
        <i class = "glyphicon glyphicon-warning-sign"></i>
        <%= pluralize(@post.errors.count, "error") %> prevented this post from saving
      </h1>
        <ol>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ol>
      </div>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control'  %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :category_ids %><br>
    <p><%= f.collection_check_boxes :category_ids, Category.all, :id, :name %></p>
  </p>
  <p>
    <%= f.submit class: 'btn btn-success'  %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id = 'page_wrapper'>
  <h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/posts/favourite.js.erb
$('#post_<%= @post.id %>').toggleClass('text-info').toggleClass('text-muted');

app/views/posts/index.html.erb
<center>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</center>
<div id="page_wrapper">
  <% @posts.each do |post| %>
    <div class="col-md-4 col-xs-6">
      <div class="thumbnail">
        <center>
          <p class="image">
            <%= image_tag post.image.url(:medium), class: 'img-rounded blog_index_img' %>
          </p>
        </center>
        <div class="caption">
          <h4><%= link_to post.title, post %></h4>
          <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
          <p><b>Category:</b>
          <% post.categories.each do |category| %>
            <%= category.name %>
          <% end %></p>
          <p>
          <% if current_user %>
            <%= link_to favourite_post_path(post), id: "post_#{post.id}", class: favourite_post(post), remote: true do %>
              <span>Like <i class = "glyphicon glyphicon-heart"></i></span>
            <% end %>
          <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div id='page_wrapper'>
  <h1>New post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id='post_content'>
  <div class='well well_post'>
    <h1 class = 'title'>
      <%= @post.title%>
    </h1>
    <p>
      <%= image_tag @post.user.avatar.url(:small), class: 'img-circle' %> 
      <%= @post.user.email %>.
    </p>
    <p class = 'date'>
      <i>Submitted <%= time_ago_in_words(@post.created_at) %> Ago</i>
      <% if require_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: 'label label-warning' %> |
        <%= link_to 'Delete', post_path(@post), class: 'label label-danger', method: :delete, data:   {confirm: 'Are you sure?'} %>
      <% end %>
    </p>
    <p><b>Category:</b>
    <% @post.categories.each do |category| %>
      <%= category.name %>
    <% end %></p>
    <p class="body">
      <%= @post.body %>
    </p>
    <p>
      <%= image_tag @post.image.url(:medium), class: "img-rounded" %>
    </p>
  
    <p>
      <h3>Views: <%= @post.page_views %></h3>
    </p>
    <p>
      <p>
        Like <i class = "glyphicon glyphicon-heart"></i>
        <%= @post.favourite_posts.count %>
      </p>
    </p>
  </div>
  <div id="comments">
    <h3><%= @post.comments.count %> Comments</h3>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id='footer'>
  <div class='col-md-6 col-md-offset-4 col-xs-12'>
    <div class='well-lg'>
      <a href='http://vk.com/crashgtafan' target='_blank'>
        <i class='fa fa-vk fa-2x'></i>
      </a>
      <a href='https://www.facebook.com/profile.php?id=100010589944972' target='_blank'>
        <i class='fa fa-facebook-square fa-2x'></i>
      </a>
      <a href='https://www.instagram.com/danilgtafan51/' target='_blank'>
        <i class='fa fa-instagram fa-2x'></i>
      </a>
      <a href='https://bitbucket.org/DanilUdalov/' target='_blank'>
        <i class='fa fa-bitbucket fa-2x'></i>
      </a>
      <a href='https://github.com/CrashGtaFan' target='_blank'>
        <i class='fa fa-github-alt fa-2x'></i>
      </a>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class='navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='
#bs-example-navbar-collapse-2'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
    </div>
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-2'>
      <ul class='nav navbar-nav'>
        <% if current_page?(root_path) %>
          <li>
            <a>All Posts</a>
          </li>
        <% elsif current_page?(about_path) %>
          <li>
            <a>About</a>
          </li>
        <% elsif current_page?(users_path) %>
          <li>
            <a>Users</a>
          </li>
        <% elsif current_page?(signup_path) %>
          <li>
            <a>Registation user</a>
          </li>
        <% elsif current_page?(login_path) %>
          <li>
            <a>Log in</a>
          </li>
        <% else %>
          <li>
            <%= link_to 'Back to All Posts', root_path %>
          </li>
        <% end %>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if current_user %>
          <li>  
          <%= current_user.email%>
          <%= image_tag current_user.avatar.url(:small), class: 'img-circle' %>
          <% if current_user.try(:admin?) %>
            <b>Admin</b>
          <% else %>
            <b>User</b> 
          </li>
          <% end %> 
          <li> <%= link_to 'New post', new_post_path %></li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-
expanded='false'> <span class='glyphicon glyphicon-bell text-default'></span></a>
            <ul class='dropdown-menu' role='menu'>
              <li>
                <%= link_to 'My profile', current_user %>
              </li>
              <li class='divider'></li>
              <li>
                <%= link_to 'Log Out', logout_path  %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign Up', signup_path %>
          </li>
          <li>
            <%= link_to 'Log In', login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id='sidebar'>
  <div id='logo'>
    <%= link_to root_path do %>
      <%= image_tag src='/assets/logo.png', class: 'img-circle' %>
    <% end %>
  </div>
  <ul>
    <li class='category'>
      My blog
    </li>
    <li>
      <%= link_to 'Blog', root_path %>
    </li>
    <% if current_admin %>
      <li>
        <%= link_to 'Admin', admin_root_path %>
      </li>
    <% end %>
    <li>
      <%= link_to 'About', about_path %>
    </li>
  </ul>
</div>

app/views/shared/admin/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="
#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Admin</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Users", admin_users_path %>
        </li>
        <li>
          <%= link_to "Posts", admin_posts_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Back to site ", root_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id='error_messages'>
      <div class='alert alert-danger' role='alert'>
        <button type='button' class='close' data-dismiss='alert'>x</button>
        <h2>
          <i class = 'glyphicon glyphicon-warning-sign'></i>
          Form is invalid
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_confirmation, class: 'form-control'%>
  </p>
  <p>
    <%= f.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div id='page_wrapper'>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id='error_messages'>
        <div class='alert alert-danger' role='alert'>
          <button type='button' class='close' data-dismiss='alert'>x</button>
          <h2>
            <i class = 'glyphicon glyphicon-warning-sign'></i>
            Form is invalid
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <p>
      <%= f.label :name %>
      <br>
      <%= f.text_field :name, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :lastname %>
      <br>
      <%= f.text_field :lastname, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :email %>
      <br>
      <%= f.text_field :email, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <br>
      <%= f.password_field :password_confirmation, class: 'form-control'%>
    </p>
    <p>
      <%= f.label :avatar %>
      <br>
      <%= f.file_field :avatar %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-success' %>
    </p>
  <% end %>
</div>

app/views/users/index.html.erb
<center>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</center>
<div id='page_wrapper'>
  <table class='table table-hover'>
    <tr>
      <td>
       <b>#</b>
     </td>
      <td>
       <b>Email</b>
     </td>
      <td>
       <b>Avatar</b>
     </td>
      <td></td>
    </tr>
    <% @users.each do |user| %>
      <div class='user_wrapper'>
        <tr>
          <td>
            <%= user.id %>
          </td>
          <td>
            <%= link_to user.email, user %>
          </td>
          <td>
            <%= image_tag user.avatar.url(:small), class: 'img-circle' %>
          </td>
          <td>
            <h4>
            <% if user.admin %>
              <%= link_to 'make user', change_permission_user_path(user), class: 'label label-primary'%>
            <% else %>
              <%= link_to 'make admin', change_permission_user_path(user), class: 'label label-warning' %>
            <% end %>
              <%= link_to 'Delete', user_path(user), class: ' label label-danger', method: :delete, data: {  confirm: 'Are you sure?'} %></h4>
          </td>
        </tr>
      </div>
    <% end %>
  </table>
</div>
<center>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</center>

app/views/users/new.html.erb
<div id='page_wrapper'>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div id='page_wrapper'>
  <h1 class = 'title'>
    <%= @user.name %>
    <%= @user.lastname %>
  </h1>
  <b>Full name:</b><p><%= @user.name %>  <%= @user.lastname %>.</p>
  <b>Email:</b><p><%= @user.email %>.</p>
  <p>
    <%= image_tag @user.avatar.url(:medium) %>
  </p>
  <p>
    <button class='button'>
      <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-warning' %>
    </button>
  </p>
</div>